version: 2
jobs:
  # Testing Node 8; running Yarn, ESLint, Flow and Jest
  test-node-8:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - node8-dependencies-{{ checksum "yarn.lock" }}
          - node8-dependencies-
      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap
      - run: (cd packages/react-qml-renderer && yarn build)
      - run: yarn test:ci
      - save_cache:
          paths:
            - node_modules
          key: node8-dependencies-{{ checksum "yarn.lock" }}

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  node-8:
    jobs:
      - test-node-8
